### PR TITLE
Remove obsolete on-boarding message parameter

### LINKED ISSUE #207: What is createOnboardingMsg supposed to do
When adding the identity wallet, we ended up modifying createOnboardingMsg() :
https://github.com/trustlines-network/clientlib/blob/develop/src/User.ts#L153.
We changed its input from `ethersKeystore` to `serializedWallet` but were unsure of what the function is used for and if it needs to be modified / deleted.

My understandingis that it is used to create a message to ask for ETH to another user. It takes as input the ethersKeystore to be able to recover the address that should receive the eth. This is not necessary as it could use `this.address`.

### PR DESCRIPTION
**Pull request by weilbith**
Closes #207

### CODE REVIEW

**Comment by weilbith** [comment]
I'm a bit confused. Yes, one line will not executed anymore, since it has been removed. So the `Lines` as well as the `Hits` value has decreased. But I thought the coverage should be relative and not absolute.
I'm not sure what in [this metric](https://docs.codecov.io/docs/about-code-coverage#section-what-is-code-coverage) is the difference between `hits` and `sum of hit`. Probably this is a double notation of `sum of` and `+ ... +`.
> hits / (sum of hit + partial + miss)

This is for me this results into this:

|   | hits | sum of ... | coverage |
|:---:|:---:|:---:|:---:|
| develop | 589 | 892 | 0,66 |
| fix/... | 588 | 891 | 0,66 |

**Comment by cducrest** [comment]
Your result is correct, I don't see what confuses you:
589/892 = 66.03
588/891 = 65.99
66.03 - 65.99 = 0.04

We lose 0.04% test coverage by removing one line that was previously covered.

Otherwise lgtm

**Comment by berndbohmeier** [comment]
Maybe stop rounding?^^

**Comment by weilbith** [comment]
Time for a new calculation tool. Too primitive it seems like.
I'm still confused why it is this way. I mean it makes sense from the math perspective. But in fact the coverage itself from the higher view hasn't changed. Anyway doesn't matter. Now I know that I have to check this value twice if I see the coverage has dropped.

**Pull request merged**
