### PR TITLE
Fix setup file for e2e tests to work with new deploy commandline

### PR DESCRIPTION
**Pull request by berndbohmeier**
Fixes the tests to work with new deploy script, see https://github.com/trustlines-network/contracts/pull/111

### CODE REVIEW

**Comment by dakingha69** [comment]
The problem is that `currencyNetwork.getAll` returns Currency Network only with high-level infomation:
```
{
  abbreviation: ...,
  name: ...,
  address: ....
}
```
Either we include decimals into the endpoint `/networks` or we randomly pick networks for the tests.

**Comment by berndbohmeier** [comment]
Is it important that they have 2 decimals?

**Comment by dakingha69** [comment]
No not really... We can then just take the first 2 networks in the test for now.

**Comment by berndbohmeier** [comment]
Perfect. Lgtm

**Pull request merged**
